name: CheatDetector
version: 1.0.0
main: de.jules.cheatdetector.CheatDetectorPlugin
api-version: '1.21'
author: Jules
description: A plugin to detect cheat clients.
commands:
  cybercheat:
    description: "Opens the cheat detection GUI."
    usage: "/cybercheat"
    permission: "cybercheat.command"
